//! Generates the `coolicons-gen.slint` library file inside `OUT_DIR`.
//!
//! The generated file exposes two globals:
//! - `CoolIcons`: one `image` property per UI icon (SVG copies, tinted in Slint via `colorize`)
//! - `AppArt`: pre-rendered plated PNGs (window icon, About logo, tray icons)
//!
//! Import it from `.slint` code with `import { CoolIcons, AppArt } from "@coolicons";`
//! after registering the file as library path `coolicons` in slint-build.

use std::fmt::Write as _;
use std::path::{Path, PathBuf};

use crate::coolicons::{Coolicons, IconRef};
use crate::icon::{self, PlateStyle};

/// A UI icon exposed as `CoolIcons.<property>`.
#[derive(Debug, Clone, Copy)]
pub struct UiIcon {
    pub property: &'static str,
    pub icon: IconRef,
}

/// A plated PNG exposed as `AppArt.<property>`.
#[derive(Debug, Clone, Copy)]
pub struct ArtImage {
    pub property: &'static str,
    pub icon: IconRef,
    pub style: PlateStyle,
    pub size: u32,
}

/// Paths of the generated files.
#[derive(Debug, Clone)]
pub struct Generated {
    /// `OUT_DIR/gen`
    pub dir: PathBuf,
    /// `OUT_DIR/gen/coolicons-gen.slint`
    pub slint_file: PathBuf,
}

/// Copies the UI icons, renders the art PNGs and writes the `.slint` library file.
pub fn generate(
    coolicons: &Coolicons,
    out_dir: &Path,
    ui_icons: &[UiIcon],
    art: &[ArtImage],
) -> Generated {
    let all: Vec<IconRef> = ui_icons
        .iter()
        .map(|u| u.icon)
        .chain(art.iter().map(|a| a.icon))
        .collect();
    coolicons.require(&all);

    let dir = out_dir.join("gen");
    let mut slint = String::from(
        "// @generated by wol-build at build time from coolicons (CC BY 4.0).\n\
         // Do not edit and never commit this file or the assets next to it.\n\n\
         export global CoolIcons {\n",
    );
    for u in ui_icons {
        let file = u.icon.flat_file_name();
        let svg = coolicons.read_svg(u.icon);
        crate::write_if_changed(&dir.join("icons").join(&file), svg.as_bytes())
            .expect("write icon copy");
        let _ = writeln!(
            slint,
            "    out property <image> {}: @image-url(\"icons/{file}\");",
            u.property
        );
    }
    slint.push_str("}\n\nexport global AppArt {\n");
    for a in art {
        let file = format!("{}.png", a.property);
        let svg = coolicons.read_svg(a.icon);
        icon::write_png(&dir.join("art").join(&file), &svg, a.style, a.size)
            .expect("render art png");
        let _ = writeln!(
            slint,
            "    out property <image> {}: @image-url(\"art/{file}\");",
            a.property
        );
    }
    slint.push_str("}\n");

    let slint_file = dir.join("coolicons-gen.slint");
    crate::write_if_changed(&slint_file, slint.as_bytes()).expect("write coolicons-gen.slint");
    Generated { dir, slint_file }
}
